vich_uploader:
    db_driver: orm
    mappings:
        user:
            uri_prefix: /uploads/files
            upload_destination: '%kernel.project_dir%/public_html/uploads/files'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
