#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
  path: /logout
# config/routes.yaml
dashboard:
  path: /admin
  controller: App\Controller\Admin\DashboardController::index