# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

imports:
    - { resource: custom_services.yaml }

parameters:
    app.supported_locales: 'en|ru'
    router.request_context.host: '%env(default:default_domain:SYMFONY_DEFAULT_ROUTE_HOST)%'
    router.request_context.scheme: '%env(default:default_scheme:SYMFONY_DEFAULT_ROUTE_SCHEME)%'
    default_admin_email: info@smcentr.su
    noreply_email: noreply@smcentr.su
    default_subject: Subject from site smcentr.su
    default_domain: 'smcentr.su'
    default_scheme: 'https'
    firebase_api_key: ''
    project_id: '1'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
          $targetDirectory: "%kernel.project_dir%/public_html/uploads/files"
          $adminEmail: "%env(string:default:default_admin_email:ADMIN_EMAIL)%"
          $noreplyEmail: "%env(string:default:noreply_email:NOREPLY_EMAIL)%"
          $firebaseApiKey: "%env(string:default:firebase_api_key:FIREBASE_API_KEY)%"
          $defaultDomain: "%env(string:default:default_domain:DEFAULT_DOMAIN)%"
          $projectId: "%env(string:default:project_id:PROJECT_ID)%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #App\Entity\TaskRate:
    #  arguments: ['@doctrine.orm.entity_manager']