name: ddev-smcentrsu
networks:
  ddev_default:
    external: true
    name: ddev_default
  default:
    name: ddev-smcentrsu_default
services:
  db:
    build:
      args:
        BASE_IMAGE: drud/ddev-dbserver-mariadb-10.4:v1.21.4
        gid: "1000"
        uid: "1000"
        username: dmitry
      context: /home/dmitry/Work/Cygenic/smcentr_symfony/src/.ddev/.dbimageBuild
      dockerfile: Dockerfile
    command: []
    container_name: ddev-smcentr.su-db
    environment:
      COLUMNS: "271"
      DDEV_DATABASE: mariadb:10.4
      DDEV_HOSTNAME: smcentr.su.ddev.site
      DDEV_PHP_VERSION: "7.4"
      DDEV_PRIMARY_URL: https://smcentr.su.ddev.site
      DDEV_PROJECT: smcentr.su
      DDEV_PROJECT_TYPE: php
      DDEV_ROUTER_HTTP_PORT: "80"
      DDEV_ROUTER_HTTPS_PORT: "443"
      DDEV_SITENAME: smcentr.su
      DDEV_TLD: ddev.site
      DOCKER_IP: 127.0.0.1
      GOARCH: amd64
      GOOS: linux
      HOST_DOCKER_INTERNAL_IP: ""
      IS_DDEV_PROJECT: "true"
      LINES: "71"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/smcentr.su-db/mysql_history
      MYSQL_PWD: db
      PGDATABASE: db
      PGHOST: 127.0.0.1
      PGPASSWORD: db
      PGUSER: db
      POSTGRES_DB: db
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
      TZ: ""
      USER: dmitry
    healthcheck:
      interval: 1s
      retries: 120
      start_period: 2m0s
      timeout: 2m0s
    hostname: smcentr.su-db
    image: drud/ddev-dbserver-mariadb-10.4:v1.21.4-smcentr.su-built
    labels:
      com.ddev.app-type: php
      com.ddev.approot: /home/dmitry/Work/Cygenic/smcentr_symfony/src
      com.ddev.platform: ddev
      com.ddev.site-name: smcentr.su
    networks:
      ddev_default: null
      default: null
    ports:
    - host_ip: 127.0.0.1
      mode: ingress
      protocol: tcp
      published: "0"
      target: 3306
    restart: "no"
    stop_grace_period: 1m0s
    user: 1000:1000
    volumes:
    - source: database
      target: /var/lib/mysql
      type: volume
      volume:
        nocopy: true
    - bind:
        create_host_path: true
      source: /home/dmitry/Work/Cygenic/smcentr_symfony/src/.ddev
      target: /mnt/ddev_config
      type: bind
    - bind:
        create_host_path: true
      source: /home/dmitry/Work/Cygenic/smcentr_symfony/src/.ddev/db_snapshots
      target: /mnt/snapshots
      type: bind
    - source: ddev-global-cache
      target: /mnt/ddev-global-cache
      type: volume
      volume: {}
    working_dir: /home/dmitry
  dba:
    container_name: ddev-smcentr.su-dba
    environment:
      HTTP_EXPOSE: 8036:80
      HTTPS_EXPOSE: 8037:80
      PMA_PASSWORD: root
      PMA_USER: root
      TZ: ""
      UPLOAD_LIMIT: 1024M
      VIRTUAL_HOST: smcentr.su.ddev.site
    expose:
    - "80"
    healthcheck:
      interval: 2m0s
      retries: 1
      timeout: 2s
    hostname: smcentr.su-dba
    image: phpmyadmin:5
    labels:
      com.ddev.app-type: php
      com.ddev.approot: /home/dmitry/Work/Cygenic/smcentr_symfony/src
      com.ddev.platform: ddev
      com.ddev.site-name: smcentr.su
    networks:
      ddev_default: null
      default: null
    restart: "no"
    working_dir: /root
  web:
    build:
      args:
        BASE_IMAGE: drud/ddev-webserver:v1.21.4
        gid: "1000"
        uid: "1000"
        username: dmitry
      context: /home/dmitry/Work/Cygenic/smcentr_symfony/src/.ddev/.webimageBuild
      dockerfile: Dockerfile
    cap_add:
    - SYS_PTRACE
    container_name: ddev-smcentr.su-web
    environment:
      COLUMNS: "271"
      DDEV_COMPOSER_ROOT: /var/www/html
      DDEV_DATABASE: mariadb:10.4
      DDEV_DOCROOT: public_html
      DDEV_FILES_DIR: ""
      DDEV_HOSTNAME: smcentr.su.ddev.site
      DDEV_PHP_VERSION: "7.4"
      DDEV_PRIMARY_URL: https://smcentr.su.ddev.site
      DDEV_PROJECT: smcentr.su
      DDEV_PROJECT_TYPE: php
      DDEV_ROUTER_HTTP_PORT: "80"
      DDEV_ROUTER_HTTPS_PORT: "443"
      DDEV_SITENAME: smcentr.su
      DDEV_TLD: ddev.site
      DDEV_VERSION: v1.21.4
      DDEV_WEBSERVER_TYPE: nginx-fpm
      DDEV_XDEBUG_ENABLED: "false"
      DEPLOY_NAME: local
      DOCKER_IP: 127.0.0.1
      DOCROOT: public_html
      DRUSH_ALLOW_XDEBUG: "1"
      DRUSH_OPTIONS_URI: https://smcentr.su.ddev.site
      GOARCH: amd64
      GOOS: linux
      HOST_DOCKER_INTERNAL_IP: ""
      HTTP_EXPOSE: 80:80,8025:8025
      HTTPS_EXPOSE: 443:80,8026:8025
      IS_DDEV_PROJECT: "true"
      LINES: "71"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/smcentr.su-web/mysql_history
      MYSQL_PWD: db
      NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
      PGDATABASE: db
      PGHOST: db
      PGPASSWORD: db
      PGUSER: db
      PHP_IDE_CONFIG: serverName=smcentr.su.ddev.site
      SSH_AUTH_SOCK: /home/.ssh-agent/socket
      TZ: ""
      USER: dmitry
      VIRTUAL_HOST: smcentr.su.ddev.site
      npm_config_cache: /mnt/ddev-global-cache/npm
    external_links:
    - ddev-router:smcentr.su.ddev.site
    extra_hosts:
      host.docker.internal: host-gateway
    healthcheck:
      interval: 1s
      retries: 120
      start_period: 2m0s
      timeout: 2m0s
    hostname: smcentr.su-web
    image: drud/ddev-webserver:v1.21.4-smcentr.su-built
    labels:
      com.ddev.app-type: php
      com.ddev.approot: /home/dmitry/Work/Cygenic/smcentr_symfony/src
      com.ddev.platform: ddev
      com.ddev.site-name: smcentr.su
    networks:
      ddev_default: null
      default: null
    ports:
    - host_ip: 127.0.0.1
      mode: ingress
      protocol: tcp
      target: 80
    - host_ip: 127.0.0.1
      mode: ingress
      protocol: tcp
      target: 443
    restart: "no"
    user: 1000:1000
    volumes:
    - consistency: cached
      source: ../
      target: /var/www/html
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /home/dmitry/Work/Cygenic/smcentr_symfony/src/.ddev
      target: /mnt/ddev_config
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /home/dmitry/Work/Cygenic/smcentr_symfony/src/.ddev/xhprof
      target: /usr/local/bin/xhprof
      type: bind
    - source: ddev-global-cache
      target: /mnt/ddev-global-cache
      type: volume
      volume: {}
    - source: ddev-ssh-agent_socket_dir
      target: /home/.ssh-agent
      type: volume
      volume: {}
    working_dir: /var/www/html/
volumes:
  database:
    external: true
    name: smcentr.su-mariadb
  ddev-global-cache:
    external: true
    name: ddev-global-cache
  ddev-ssh-agent_socket_dir:
    external: true
    name: ddev-ssh-agent_socket_dir
